language: python

sudo: true

python: 3.7

services:
  - docker

addons:
  hosts:
    - fbf.test

before_install:
  - sudo apt -y update; sudo apt -y install wget curl
  - sudo bash extract-interface-ip.sh
  - sudo bash modify-dnsmasq-config.sh
  - docker-compose build
  - docker-compose up -d

script:
  # initiate fake server
  - python -m http.server --bind 0.0.0.0 80 &
  - sleep 10
  - wget http://fbf.test/
  - curl http://fbf.test/
  - docker-compose exec node wget http://fbf.test/
  - docker-compose exec node curl http://fbf.test/

  - python -m http.server --bind 0.0.0.0 8080 &
  - sleep 10
  - wget http://fbf.test:8080/
  - curl http://fbf.test:8080/
  - docker-compose exec node wget http://fbf.test:8080/
  - docker-compose exec node curl http://fbf.test:8080/
