language: python

sudo: true

python: 3.7

services:
  - docker

addons:
  hosts:
    - fbf.test

before_install:
  - sudo apt -y update; sudo apt -y install wget curl
  - sudo bash extract-interface-ip.sh
  - export IP_ADDR=$(cat ip-address.txt)
  - echo $IP_ADDR
  - sudo bash modify-dnsmasq-config.sh
  - docker-compose build
  - docker-compose up -d

script:
  # initiate fake server
  # For some reason, we can't use port 80
  - python -m http.server --bind 0.0.0.0 8080 &
  - sleep 10
  - wget http://fbf.test:8080/
  - curl http://fbf.test:8080/
  - docker-compose exec node wget http://fbf.test:8080/
  - docker-compose exec node curl http://fbf.test:8080/
  - docker-compose exec node wget http://postgrest.fbf.test:8080/
  - docker-compose exec node curl http://postgrest.fbf.test:8080/
  - docker-compose exec node-in-bridge wget http://fbf.test:8080/
  - docker-compose exec node-in-bridge curl http://fbf.test:8080/
  - docker-compose exec node-in-bridge wget http://postgrest.fbf.test:8080/
  - docker-compose exec node-in-bridge curl http://postgrest.fbf.test:8080/
  - sudo netstat -tulnp
